In [1]:
%history

%history


In [3]:
sum([1,2,3])

6

In [4]:
%history

%history
sum[1,2,3]
sum([1,2,3])
%history


In [1]:
!touch myfile.py
# this is a linux command and will not work in windows

'touch' is not recognized as an internal or external command,
operable program or batch file.


In [3]:
%time sum([1,2,3])

Wall time: 0 ns


6

# Numpy Vs Python

In [ ]:
%time l1= list(range(1,2000000))

In [10]:
 # adding number in a list method 1 using loop
%time [x+5 for x in l1] [:10]

Wall time: 176 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [12]:
enumerate(['a','b','c','d'])

In [13]:
list(enumerate(['a','b','c','d']))

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]

In [16]:
# adding number is a list usign enumerate and then loop
for i,v in list(enumerate(l1)):
    l1[i] = l1[i]+5
    
l1[0:10]

[16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

## numpy

In [6]:
import numpy as np

In [26]:
%time l2 = np.arange(1,3000000)

Wall time: 9.97 ms


In [27]:
%time l2 + 5

Wall time: 8.98 ms


array([      6,       7,       8, ..., 3000002, 3000003, 3000004])

In [18]:
# you have actually broadcasted a number over whole array

In [28]:
# printing dimension shape and type of array
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("type:", l2.dtype)

Dimension: 1
Shape: (2999999,)
type: int32


In [29]:
l3 = np.random.randn(2,2)
print(l3)
print("Dimension:", l3.ndim)
print("Shape:", l3.shape)
print("type:", l3.dtype)

[[0.92626009 0.74504825]
 [1.43089898 0.60280708]]
Dimension: 2
Shape: (2, 2)
type: float64


In [57]:
l4 = np.random.randn(3,4,5)
print(l4)
print("Dimension:", l4.ndim)
print("Shape:", l4.shape)
print("type:", l4.dtype)
print("type:", l4.itemsize)   # tells number of bits

[[[ 0.7028066  -0.01125795  0.39502987  1.37561192  0.964523  ]
  [-0.08250256 -0.87801054 -1.26653564 -0.43622609  1.00456187]
  [-0.11216798 -0.72639195 -1.11586273  0.6190969   0.48909521]
  [ 0.81928943  1.03220522  1.22679373  0.95338775 -1.75257255]]

 [[ 0.18086414  0.08299777 -1.75961031 -0.29240136  0.13019145]
  [ 1.19097649  0.15948388  0.74866828 -0.54742315 -0.58845389]
  [ 0.97517339  0.16609264 -0.62171184  0.0659363  -0.76874128]
  [ 1.4545498  -2.1041436   0.08459816 -1.12829163 -0.05347263]]

 [[-0.13633765 -0.28147884 -0.78356313 -1.30448898  1.03838161]
  [ 0.61815222 -0.32236295  2.01310303 -0.49085301  1.47777839]
  [ 0.21543291 -0.40181103 -0.39282326  0.59916741 -1.00418322]
  [-0.37554341  2.22300636  1.29148377  0.3514078   0.78919567]]]
Dimension: 3
Shape: (3, 4, 5)
type: float64
type: 8


In [ ]:
# columns are in rows. and rows are in dimensions or axis. 
# so in above we have 3 dimensions or 3 axis
# then 4 rows in each dimension
# then 5 columns
# if

In [41]:
l5 = np.arange(1,25)
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [43]:
l6 = np.arange(25)
l6
# means if starting point is not given to range. then it starts from 0
# range has 3 eleemnts. start end(not included) and step

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
l7 = np.arange(27).reshape(3,3,3)
l7
# we reshaped that array into dimensions of 3,3,3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

<img src='https://www.pythoninformer.com/img/numpy/3d-array.png'>

In [45]:
# we use markup of <img src="url"> here. from GIT markdown


In [46]:
# i,j,k means
# i is dimension        j is rows  k is columns
# RGB red green blue



# slicing a 3 dimension arrange

In [49]:
 # to slice them use the similar index. indexing starts form 0
# 0 dimentsion, 0 row, 0 column
    l7 = np.arange(27).reshape(3,3,3)
l7
print(l7[0,0,0])
print(l7[1,1,1])
print(l7[2,2,2])

0
13
26


# reshaping arrays

In [55]:
# arrange can be reshaped into all posssible combinations
l8 = np.arange(1,13).reshape(1,12)
print(l8)
print('-------------------------')
l8 = np.arange(1,13).reshape(2,6)
print(l8)
print('-------------------------')
l8 = np.arange(1,13).reshape(3,4)
print(l8)
print('-------------------------')
l8 = np.arange(1,13).reshape(4,3)
print(l8)
print('-------------------------')
l8 = np.arange(1,13).reshape(6,2)
print(l8)
print('-------------------------')
l8 = np.arange(1,13).reshape(12,1)
print(l8)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
-------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
-------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-------------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
-------------------------
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [72]:
l8 = np.arange(1,13).reshape(3,4)
print(l8)          # show all
print("--------------")
print(l8 % 2 == 0)  # check only where remainder should be 0 if divided by 2  as true false
print("--------------")
print(l8[l8 % 2 == 0])  # slice and then print only where remainder should be 0 if divided by 2  as true false

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
--------------
[ 2  4  6  8 10 12]


# np.array always makes a deep copy

In [77]:
l1 = [1,2,3]
a = np.array(l1)         # np.array makes a deep copy. a new physical address and new copy in reference
# to check this. lets assign this to b. and check if they are equal

b = np.array(a)
print(a)

print(a is b)

[1 2 3]
False


# np.asarray makes a shallow copy or deep copy

In [84]:
#1 ifalready array -->>> no change in data type -->> makes a shallow copy if input is already an array
#2 if already array >>>>> datea type changed--->>>   means not an array already
#3 if not array --->> makes deep copy
l1 = [1,2,3]
a = np.asarray(l1)         
b = np.asarray(a)
c = np.asarray(a, dtype=np.float64)
print(a)

print(l1 is a)   #1 this is deep copy   so false
print(a is b)    #2 this is shallow copy so true
print(c is a)  #3 this is again a deep copy

[1 2 3]
False
True
False


## built in data type in the a range function 

In [ ]:
 a = np.arange()