In [1]:
import numpy as np

In [15]:
names = np.array(["Imran","Qasim","Ali","Imran","Shoaib","Ali"])
data = np.random.randn(6,4)
print(names,data, sep="\n")

#you can view it as these are columns

['Imran' 'Qasim' 'Ali' 'Imran' 'Shoaib' 'Ali']
[[ 1.08229233  1.69643135  0.52449093 -0.42819914]
 [ 0.54214909  1.63920893 -0.47945873  0.69382822]
 [-0.564865    1.37580461 -0.64999863  0.63295581]
 [-0.6394648   0.2179277   0.31429097 -0.62677857]
 [ 0.44288312  0.81873615  1.56598936  1.15799833]
 [ 0.42858372  0.14425648 -1.15434786 -1.15339697]]


In [16]:
names=="Imran"

array([ True, False, False,  True, False, False])

In [19]:
data[[True,False, False,True, False,False]]

array([[ 1.08229233,  1.69643135,  0.52449093, -0.42819914],
       [-0.6394648 ,  0.2179277 ,  0.31429097, -0.62677857]])

In [20]:
data[names=="Imran"]  # using direct method all data where names are imran. like all links where class=imran

array([[ 1.08229233,  1.69643135,  0.52449093, -0.42819914],
       [-0.6394648 ,  0.2179277 ,  0.31429097, -0.62677857]])

In [24]:
data[names=="Imran"][:,[-1,0,3]]  # using column numbers to further pick from already sliced index

array([[-0.42819914,  1.08229233, -0.42819914],
       [-0.62677857, -0.6394648 , -0.62677857]])

# Fancy Slicing

In [27]:
# in fancy slicing we can pass elements in any dimension using square bracket
a=np.arange(3*3*3).reshape(3,3,3)
print(a)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
a=np.arange(3*3*3).reshape(3,3,3)
#print(a[slide,row,column])  you can choose multiple slides/dimensions multiple columnsb y again usign []
#  use    :  for all rows or all columns
print(a[[-1,-2,0]])

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [33]:
print(a[[-1,-2,0],:,:])

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


# slicing and then updating the slicec value

In [43]:


a=np.arange(3*3*3).reshape(3,3,3)
print(a)
print("\n")
a[1]=5
a

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]




array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 5,  5,  5],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
names = np.array(["Col1","Col2","Col3","Col4","Col5","Col6"])
data = np.random.randn(6,4)

data[names=="Col1"]

array([[ 0.66439474,  0.20260603,  0.15028176, -0.97351087]])

# Slicing works from left to right
# like vlookup
# jahan se start hoga wahan se agay se slice hoga

In [53]:
names = np.array(["Col1","Col2","Col3","Col4","Col5","Col6"])
data = np.random.randn(6,4)
data

array([[-2.37810051,  0.19127259, -0.85948054,  1.38379958],
       [ 0.53849713, -2.14293099, -1.16817329, -0.62355001],
       [ 0.04824718, -0.46400464,  0.10515472, -0.09686056],
       [-0.20891814,  0.50660211, -0.20323733, -0.37724805],
       [ 0.19525299,  0.96289521,  1.29232177,  0.44999818],
       [-1.33039826, -0.20182507,  1.36059606, -0.60949785]])

In [55]:
data[:,::-1]   # means all rows, then all columns,  then step is -1

array([[ 1.38379958, -0.85948054,  0.19127259, -2.37810051],
       [-0.62355001, -1.16817329, -2.14293099,  0.53849713],
       [-0.09686056,  0.10515472, -0.46400464,  0.04824718],
       [-0.37724805, -0.20323733,  0.50660211, -0.20891814],
       [ 0.44999818,  1.29232177,  0.96289521,  0.19525299],
       [-0.60949785,  1.36059606, -0.20182507, -1.33039826]])

# slicing using loop

In [57]:
a = np.arange(8*4).reshape(8,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [61]:
a = np.arange(8*4).reshape(8,4)
for i in range(len(a)):
    print(i)   # this will pick on row
    

0
1
2
3
4
5
6
7


In [63]:
a = np.arange(8*4).reshape(8,4)
for i in range(len(a)):
    a[i]=i
print(a)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [67]:
a = np.arange(8*4).reshape(8,4)
for i, _ in enumerate(a):            # suing _ instead of a value puts that variable in garbage
    a[i] = i
print(a)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


# Tranposing Arrays and Swappig Axes

In [71]:
a = np.arange(3*4).reshape(3,4)
print(a)
print()

print(a.T)     # using attribute T for transpose

print()
print(a.transpose())   # we an also use mthod of transpose

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Element wise multiplication and dot product multiplcation 