In [2]:
import numpy as np

In [5]:
a= np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
# Chaining system  or nesting system
#A(B(C(1)))   in normal python


#A().B().C()  in numpy  check sequence which function will be called first
#np.arange().reshape()  means first arange will be called then its result will be passed to reshape


In [9]:
a= np.arange(1,13).reshape(3,4)
print(a)
print(a.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
int32


In [11]:
#Optimizing Technique

a= np.arange(1,13).reshape(3,4).astype('float64')
print(a)
print(a.dtype)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
float64


In [12]:
# change seqeunce of chain
a= np.arange(1,13).astype('float64').reshape(3,4)
print(a)
print(a.dtype)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
float64


# numpy.arange(start, stop, step, dtype)

In [19]:
#use less functions and try more builtin attributes
b=np.arange(1,13,1,'float64')
print(b)
print(b.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
float64


In [24]:
#randn is used for normal distribution of any number
c = np.random.randn(3,3) * 5
c

array([[-4.03119691, -3.00872554, -4.36168706],
       [ 0.93994298, -1.46700978, -1.66584319],
       [-1.484321  , -0.28666587,  2.36409898]])

In [28]:
a = np.ones((3,3,3))
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int64)

In [31]:
# this will make a new array with dimensions of the given array in like funtion
# why its used. you are uploading an image and want to load it using already extablished dimensions set in another array
np.ones_like(a) * 5

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]], dtype=int64)

In [32]:
# this above funtion is good but still we are using two operation
#sin it. to generate an array of only five we can do that using one funtion only

np.full((3,3,3),5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [33]:
# now make an array of 10 but with dimentiosn of already present array 'a'

np.full_like(a,10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]], dtype=int64)

In [34]:
np.empty((3,3,3))  # returns 0 and the garbage values randomly 

array([[[ 1.50008929e+248,  1.06396443e+224,  1.47765135e+248],
        [ 4.30625279e-096,  9.08366793e+223,  1.21458896e-046],
        [ 3.14380975e+179,  5.49172066e+174,  8.76176610e+169]],

       [[ 2.24729315e+174,  1.56605686e-076,  4.75387337e-038],
        [ 6.36601121e-062,  4.17823968e-062,  1.28625693e+248],
        [ 4.24948967e-086,  4.05171132e-317, -4.89084377e-311]],

       [[ 8.25168414e-312,  9.18962101e-322,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  5.02034658e+175],
        [ 1.41632743e-076,  1.20129735e-075,  6.88513329e-042]]])

### identity matrix

In [35]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [40]:
np.eye??   # to see full syntax

In [39]:
np.identity??

In [41]:
# np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
#np.identity(n, dtype=None)

# Data types for ndarray

In [47]:
a = np.arange(1,13,dtype='int64')
print(a.dtype)

int64


In [48]:
a = np.arange(1,13,dtype=np.int32)
print(a.dtype)

int32


In [50]:
a = np.arange(1,13,dtype='i8')
print(a.dtype)

int64


In [51]:
# same array but new data type in a new variable.
#drawback less efficient as compared to all aboe

a.astype(np.float64)            
print(a.dtype)

int64


# Slicing using Boolean

In [58]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [59]:
a%3 ==0   # using module divisible by 3 will retun

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [60]:
a[a%3==0]    # now if you passabove in a it will auto slice the one which are true

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [69]:
# | used for or
# & used for and
# ~ used for not equal to . called ternary operator applied on numpy array only. not on individual elements
a[(a%3==0)  | (a%5==0)]

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27])

In [70]:
a[(a%3==0) & (a%5==0)]

array([15])

In [71]:
a[~(a%3==0)]  # all numbers that are not in table of 3

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

# Basic Indexing and Slicing